// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package repo

import (
	"context"
	"database/sql"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (user_id, collection_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, collection_id, title, description, created_at
`

type CreateCardParams struct {
	UserID       int64
	CollectionID int64
	Title        string
	Description  sql.NullString
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.UserID,
		arg.CollectionID,
		arg.Title,
		arg.Description,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id=$1 AND user_id=$2
`

type DeleteCardParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) error {
	_, err := q.db.ExecContext(ctx, deleteCard, arg.ID, arg.UserID)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, user_id, collection_id, title, description, created_at FROM cards
WHERE id = $1 AND user_id = $2
`

type GetCardParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CollectionID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCards = `-- name: GetCards :many
SELECT id, user_id, collection_id, title, description, created_at FROM cards
WHERE user_id = $1 AND collection_id = $2
`

type GetCardsParams struct {
	UserID       int64
	CollectionID int64
}

func (q *Queries) GetCards(ctx context.Context, arg GetCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCards, arg.UserID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CollectionID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET title = $3, description = $4
WHERE id = $1 AND user_id=$2
`

type UpdateCardParams struct {
	ID          int64
	UserID      int64
	Title       string
	Description sql.NullString
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.ExecContext(ctx, updateCard,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	return err
}
