// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package repo

import (
	"context"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at
`

type CreateCollectionParams struct {
	UserID int64
	Title  string
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.UserID, arg.Title)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1 AND user_id = $2
`

type DeleteCollectionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, arg.ID, arg.UserID)
	return err
}

const getCollectionsByUserId = `-- name: GetCollectionsByUserId :many
SELECT id, user_id, title, created_at FROM collections
WHERE user_id = $1
`

func (q *Queries) GetCollectionsByUserId(ctx context.Context, userID int64) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
