// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"
)

type Card struct {
	ID           int64
	UserID       int64
	CollectionID int64
	Title        string
	Description  sql.NullString
	CreatedAt    time.Time
}

type Collection struct {
	ID        int64
	UserID    int64
	Title     string
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
}
