// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"
)

type Collection struct {
	ID        int64
	UserID    int64
	Title     string
	CreatedAt sql.NullTime
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
}
